config/routes.rb
Rails.application.routes.draw do
  root   'documents#index'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :documents
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:project_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Registration successful!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul class="list-group">
      <% document.errors.full_messages.each do |message| %>
        <li class="list-group-item"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_id, 'Project ID' %>
    <%= f.text_field :project_id, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Submit', :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<hr>

<%= link_to 'Show', @document, :class => 'btn btn-default' %> |
<%= link_to 'Back', documents_path, :class => 'btn btn-default' %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Project ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.project_id %></td>
        <td class='center'><%= link_to 'Show', document, :class => 'btn btn-default' %></td>
        <% if logged_in? %>
        <td class='center'><%= link_to 'Edit', edit_document_path(document), :class => 'btn btn-default' %></td>
        <td class='center'><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if logged_in? %>
  <%= link_to 'New Document', new_document_path, :class => 'btn btn-default' %>
<% end %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<hr>

<%= link_to 'Back', documents_path, :class => 'btn btn-default' %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project ID:</strong>
  <%= @document.project_id %>
</p>

<% if logged_in? %>
<%= link_to 'Edit', edit_document_path(@document), :class => 'btn btn-default' %> |
<% end %>
<%= link_to 'Back', documents_path, :class => 'btn btn-default' %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Civil Works Administration public works project document site
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-default navbar-fixed-top'>
  <div class='container'>
    <%= link_to 'historic document site', root_path, id: 'logo' %>
    <nav>
      <ul class='nav navbar-nav navbar-right'>
        <li><%= link_to 'Home',    root_path %></li>
        <% if !logged_in? %>
          <li><%= link_to 'Sign up', signup_path %></li>
          <li><%= link_to 'Log in',  login_path %></li>
        <% else %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class='container'>
  <% if logged_in? %>
    <p>Logged in as <strong><%= current_user.name %></strong></p>
  <% end %>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <%= render 'layouts/header' %>
  <div class='container'>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user, url: signup_path) do |f| %>
  <%= render 'shared/error_messages' %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => 'form-control' %>
  
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control' %>
  
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control' %>
  
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit "Create my account", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>